# Generated by Django 2.2.3 on 2019-07-08 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_biomodel_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='biomodel',
            name='ownerName',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='biomodel',
            name='saveDate',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 8, 10, 2, 49, 273055)),
        ),
    ]
